project:
  type: book
  output-dir: docs

book:
  title: "Mass Spec Academy"
  favicon: figs/favicon.png
  page-navigation: true
  image: figs/ExtendedGeometryLineDrawing.svg
  output-file: "Mass Spectrometry Book"
  site-url: https://massspec.academy/
  repo-url: https://github.com/EARTHTIME/MassSpecAcademy/
  repo-actions: [issue, edit]
  chapters: 
    - index.qmd
    - part: "Background"
      href: overview.qmd
      chapters: 
      - text: "Concept Review"
        href: background.qmd
      - ion_sources.qmd
    - part: "Analytical Considerations"
      chapters: 
      - baselines.qmd
      - peak_tails_abundance_sensitivity.qmd
    - part: "Isotope Systems"
      chapters:
      - Ar_Ar.qmd
      - U_Pb.qmd
      - U_Th_He.qmd
    - part: "Interpreting Data"
      chapters:
      - basic_stats_refresher.qmd
    - references.qmd
  appendices: 
    - contributing.qmd
  navbar:
    logo: figs/MSA_logo.png
    right:
      - text: "Contribute"
        href: contributing.qmd


bibliography: references.bib

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-depth: 4
    toc-expand: 3
    toc-title: "Contents"
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^https:\/\/EARTHTIME\.github\.io.*$'
    code-fold: true
  pdf: default
  
number-depth: 3